#!/bin/bash

if [ -z ${DEI_PW_FILE+x} ]; then 
    echo "DEI_PW_FILE environmental variable is not set. Re-run the install script."
    exit 1
fi

if [ -z ${DEI_USER+x} ]; then 
    echo "DEI_USER environmental variable is not set. Re-run the install script."
    exit 1
fi


# parse argument
if [ $# -eq 0 ]; then
    DIR=.
else
    DIR=$1
fi

# assume the first argument is the directory containing the job to execute
# copy the directory to the blade gateway
JOB_DIR=$(readlink -f $DIR)
JOB_FILE=$JOB_DIR/main.job

if [ ! -f $JOB_FILE ]; then
    echo "main.job file is missing!"
else
    BASE_DIR=$(basename $JOB_DIR)
    BLADE_DIR="/home/$DEI_USER/BLADE/jobs/${BASE_DIR}"
    JOB_FILE="${BLADE_DIR}/main.job"

    echo "Copying files to DEI's ssh login machine..."

    sshpass -f $DEI_PW_FILE rsync --progress -avz -e ssh "${JOB_DIR}"  $DEI_USER@login.dei.unipd.it:/home/$DEI_USER/blade/jobs

    # enqueu the job
    cmd="cd ${BLADE_DIR}; qsub main.job";
    echo $cmd | sshpass -f $DEI_PW_FILE ssh -T -o StrictHostKeyChecking=no $DEI_USER@login.dei.unipd.it
fi

