#!/bin/bash

if [ -z ${DEI_PW_FILE+x} ]; then 
    echo "DEI_PW_FILE environmental variable is not set. Re-run the install script."
    exit 1
fi

if [ -z ${DEI_USER+x} ]; then 
    echo "DEI_USER environmental variable is not set. Re-run the install script."
    exit 1
fi

# parse argument
if [ $# -eq 0 ]; then
    DIR=.
else
    DIR=$1
fi

# assume the first argument is the directory containing the job to execute
# copy the directory to the blade gateway
JOB_DIR=$(readlink -f $DIR)
BASE_DIR=$(basename $JOB_DIR)
BLADE_DIR=/home/$DEI_USER/BLADE/jobs/$BASE_DIR/
LOCAL_DIR=$JOB_DIR

FILTER_FILE='.download'


echo "Downloading ${BLADE_DIR} to ${LOCAL_DIR}..."
sshpass -f $DEI_PW_FILE rsync --info=progress2 -avz --filter=":+ ${FILTER_FILE}" --exclude="/*" -e ssh  $DEI_USER@login.dei.unipd.it:$BLADE_DIR $LOCAL_DIR
# sshpass -f ~/.deipw rsync --info=progress2 -avz --include="sweeps/" --exclude="*" -e ssh  marcongi@login.dei.unipd.it:$BLADE_DIR $LOCAL_DIR

