#!/bin/bash

if [ -z ${DEI_PW_FILE+x} ]; then 
    echo "DEI_PW_FILE environmental variable is not set. Re-run the install script."
    exit 1
fi

if [ -z ${DEI_USER+x} ]; then 
    echo "DEI_USER environmental variable is not set. Re-run the install script."
    exit 1
fi


# parse argument
if [ $# -eq 0 ]; then
    echo "ERROR: Cluster .job file not specified"
    exit 1
else
    JOB_FILE="$1"
    DIR=.
fi


JOB_DIR=$(readlink -f $DIR)
BASE_DIR=$(basename $JOB_DIR)
BLADE_DIR=/home/$DEI_USER/BLADE/jobs
LOCAL_DIR=$JOB_DIR
FILTER_FILE=$LOCAL_DIR/.upload

blade-upload $DIR


# enqueu the job
cmd="cd $BLADE_DIR/$BASE_DIR; qsub $JOB_FILE";
blade-command "$cmd"
blade-stat

