#!/bin/bash

if [ -z ${DEI_PW_FILE+x} ]; then 
    echo "DEI_PW_FILE environmental variable is not set. Re-run the install script."
    exit 1
fi

if [ -z ${DEI_USER+x} ]; then 
    echo "DEI_USER environmental variable is not set. Re-run the install script."
    exit 1
fi

# Open ssh connection to the departments' network
sshpass -f $DEI_PW_FILE ssh -o StrictHostKeyChecking=no $DEI_USER@login.dei.unipd.it
