#!/bin/bash

if [ -z ${REMOTE_ADDRESS+x} ]; then 
    echo "REMOTE_ADDRESS environmental variable is not set. Re-run the install script."
    exit 1
fi

if [ -z ${REMOTE_USER+x} ]; then 
    echo "REMOTE_USER environmental variable is not set. Re-run the install script."
    exit 1
fi

# parse argument
if [ $# -eq 0 ]; then
    DIR=.
else
    DIR=$1
fi

# assume the first argument is the directory containing the job to execute
# copy the directory to the blade gateway
JOB_DIR=$(readlink -f $DIR)
BASE_DIR=$(basename $JOB_DIR)
BLADE_DIR=/home/$REMOTE_USER/JOBS
LOCAL_DIR=$JOB_DIR
FILTER_FILE=$LOCAL_DIR/.upload

# use rsync to copy the content of the folder to blade's login server
echo "Uploading ${LOCAL_DIR} to ${BLADE_DIR}..."
rsync --info=progress2,stats2 -avz --filter=":- $FILTER_FILE" -e ssh $LOCAL_DIR/ $REMOTE_USER@$REMOTE_ADDRESS:$BLADE_DIR/$BASE_DIR 
