#!/bin/bash

if [ -z ${REMOTE_ADDRESS+x} ]; then 
    echo "REMOTE_ADDRESS environmental variable is not set. Re-run the install script."
    exit 1
fi

if [ -z ${REMOTE_USER+x} ]; then 
    echo "REMOTE_USER environmental variable is not set. Re-run the install script."
    exit 1
fi

# parse argument
if [ $# -eq 0 ]; then
    echo "ERROR: script not specified"
    exit 1
else
    JOB_FILE="$1"
    DIR=.
fi


JOB_DIR=$(readlink -f $DIR)
BASE_DIR=$(basename $JOB_DIR)
BLADE_DIR=/home/$REMOTE_USER/JOBS
LOCAL_DIR=$JOB_DIR
FILTER_FILE=$LOCAL_DIR/.upload

remote-upload $DIR

# enqueu the job
cmd="cd $BLADE_DIR/$BASE_DIR; bash $JOB_FILE";
remote-command "$cmd"

